### ISSUE TITLE
Address elements is null for search results

### ISSUE THREAD

**Issue by IamTechknow** [jeremiehuchet/nominatim-java-api#22]
Hi,

When performing a search using version 3.2, getAddressElements() returns null for an Address object. Otherwise when calling lookup(), getAddressElements() is functional.

**Comment by jeremiehuchet** [comment]
Hi @IamTechknow, 

I see one successful integration test about this : [testAddressWithDetails](https://github.com/jeremiehuchet/nominatim-java-api/blob/v3.2/src/test/java/fr/dudie/nominatim/client/JsonNominatimClientTest.java#L194) and the [travis-ci build #52](https://travis-ci.org/jeremiehuchet/nominatim-java-api/builds/79939772) is successful.

Can you provide more informations please?

**Comment by IamTechknow** [comment]
Hi, it turns out this is a non-issue, because I did not know about being able to receive address elements on a search request by calling NominatimSearchRequest.setAddress(). I simply called NominatimClient.search() with a query string. I think a javadoc could be made to clarify this and to provide documentation on the library.

**Comment by jeremiehuchet** [comment]
We can keep the issue open until the javadoc is updated. It's important! 
Thanks for your feedback

**Comment by IamTechknow** [comment]
Glad to hear. Thanks for your hard work on this library BTW
