### ISSUE TITLE
Tests in JsonNominatimClientTest failing

### ISSUE THREAD

**Issue by jackastner** [jeremiehuchet/nominatim-java-api#33]
All test in JsonNominatimClientTest.java a currently failing on branch master and release 3.3. I believe this may be related to #32 as the errors reference HTTPS (and the lack thereof). 

The initial error was `java.lang.IllegalStateException: Scheme 'https' not registered`. I attempted to resolve this by switching the scheme and URL in the test file to https. This caused a new error `org.apache.http.client.ClientProtocolException` caused by ` org.apache.http.client.CircularRedirectException: Circular redirect`. Finally, I tried allowing the client to follow circular redirects by adding 

```
httpClient.getParams().setParameter(ClientPNames.ALLOW_CIRCULAR_REDIRECTS, true);
```

to the constructor of the test class. This only caused a different error: `org.apache.http.client.ClientProtocolException` caused by `org.apache.http.client.RedirectException: Maximum redirects (100) exceeded `. 

Outputs for my test runs are linked below:

[scheme_https_not_registered.txt](https://github.com/jeremiehuchet/nominatim-java-api/files/2022999/scheme_https_not_registered.txt)
[max_redirect.txt](https://github.com/jeremiehuchet/nominatim-java-api/files/2023000/max_redirect.txt)
[circ_redirect.txt](https://github.com/jeremiehuchet/nominatim-java-api/files/2023001/circ_redirect.txt)

**Comment by jeremiehuchet** [comment]
See commit cf9b34bd8a17be013ebee7bed4471f7c90b7acba.

When you change the scheme you must also use a (SSL)SocketFactory which complies with the protocol used to communicate with the remote server.
