### ISSUE TITLE
NominatimClient.java sample code

### ISSUE THREAD

**Issue by adonnini** [jeremiehuchet/nominatim-java-api#34]
Hi,

I would like to use your nominatim java api in my Android Java app.

Would you have some sample code of how to use it that you could popint me to?

Thanks,

Alex Donnini

**Comment by jeremiehuchet** [comment]
You should take a look at the tests ([JsonNominatimClientTest.java](https://github.com/jeremiehuchet/nominatim-java-api/blob/master/src/test/java/fr/dudie/nominatim/client/JsonNominatimClientTest.java)) to see how to use it.

**Comment by adonnini** [comment]
@jeremiehuchet 
Thanks for getting back to me. I already looked at the tests. 
I don't want to use JsonNominatimClient.java. I need to use NominatimClient.java
Unless I am mistaken, all the tests are geared to the JSON version.
Thanks,
Alex Donnini

**Comment by jeremiehuchet** [comment]
JsonNominatimClient is the only way to use this library.

**Comment by adonnini** [comment]
May I ask why?
What's the use of having NominatimClient.java, then?
Thank you,
Alex Donnini

**Comment by jeremiehuchet** [comment]
NominatimClient is an interface, see http://java-design-patterns.com/principles/#hide-implementation-details

**Comment by adonnini** [comment]
In reading your code a little more carefully, I realized that your utility does not provide the kinds of functions and integration with nominatem provided by osmdroid and osmbonuspack.
My misunderstanding. Sorry for wasting your time (and mine). Good night, Alex Donnini
