### ISSUE TITLE
about updating nominatim...

### ISSUE THREAD

**Issue by mbutler-79** [jeremiehuchet/nominatim-java-api#36]
Hi,
I wanted to know how can I update nominatim without setting this line in settings/local.php :

@define('CONST_Replication_Url', 'https://planet.openstreetmap.org/replication/minute');

I mean I don't want to sync with osm, I want to update nominatim whenever I would like.
for example I have a osm data for two months ago, now I want to update them. but I don't know if I set replicarion service with above value, all data are updated from two months ago until now ?
how can I sure that updating process is correct ?

better to use this address ?
http://download.geofabrik.de/europe-updates/

Thanks in Advance

**Comment by jeremiehuchet** [comment]
Are you trying to set up a Nominatim server?
This library is a client to make the use of a Nominatim API easier from java code. It doesn't help to set up a Nominatim server.

**Comment by mbutler-79** [comment]
yep, I've set a local Nominatim server and read about updating it from this link : 
http://nominatim.org/release-docs/latest/admin/Import-and-Update/

on the other hand, I've installed this module :
pip install osmium

but i don`t know when I set Replication_Url based on minutely, even if my old nominatim data was for long time ago, all new data until now imported to my database?

**Comment by mbutler-79** [comment]
yep, I've set a local Nominatim server and read about updating it from this link : 
http://nominatim.org/release-docs/latest/admin/Import-and-Update/

on the other hand, I've installed this module :
pip install osmium

but i don`t know when I set Replication_Url based on minutely, even if my old nominatim data was for long time ago, all new data until now imported to my database?

**Comment by jeremiehuchet** [comment]
I never set up a Nominatim server, I'm afraid I won't be able to help you :disappointed: 
Maybe you should try to reach OSM mailing lists?

**Comment by mbutler-79** [comment]
yeah, I'm asking about it wherever it's possible, even asked from here (https://help.openstreetmap.org/questions/ask/)

thanks jeremiehuchet
