### ISSUE TITLE
make Address serializable

### ISSUE THREAD

**Issue by samthiriot** [jeremiehuchet/nominatim-java-api#40]
Hello & thanks for the great library! 
Nominatim requests, as part of the terms of service, to cache results in order to avoid waste of computational resources. 
Unfortunatly, the current version of Address object is not serializable. 
Would it is possible to consider to make it implement Serializable ? 

Tks !

**Comment by jeremiehuchet** [comment]
need to make a release with #30

**Comment by samthiriot** [comment]
Great, thanks!
