### ISSUE TITLE
Add minimal implementation example for request + maybe reverse request

### ISSUE THREAD

**Issue by ramsonline** [jeremiehuchet/nominatim-java-api#46]
I am a not so experienced Java Developer and i want to use this Library. 
I am currently looking through the Javadoc to find out which classes to use.

I guess that at least one code Example would be very helpful to a lot of users who are not that familiar with the library classes.
If anyone does have a working tutorial for this Library please link it. Thanks !

**Comment by jeremiehuchet** [comment]
Java development conventions made us write tests in `src/test/java`. Tests should describe the library behavior, so they are also an important part of the documentation. 

You can take a look at the tests here [src/test/java/fr/dudie/nominatim/client/JsonNominatimClientTest.java](https://github.com/jeremiehuchet/nominatim-java-apib/bba6e4784ff14844fb25030d6c1363e23f931e18/src/test/java/fr/dudie/nominatim/client/JsonNominatimClientTest.java) to see usage examples.

I think you will find out what you need there 😊

**Comment by ramsonline** [comment]
Thank you for the Support!
i'll have a Look at it in the near Future. 

The Link you added does not Work. However i found the Test class in the mentioned Tests folder. 

Maybe use this Link:
https://github.com/jeremiehuchet/nominatim-java-api/blob/master/src/test/java/fr/dudie/nominatim/client/JsonNominatimClientTest.java

**Comment by jeremiehuchet** [comment]
Thanks @ramsonline 😊  
I am closing this issue as it seems to suit you. Feel free to reopen!
